public enum Equipo{
    UNO("COE IES CALCULO FISICA PROGRAMACION DISCRETAS"), 
    DOS("BD APLICADO LINEAL DIFERENCIALES ECONOMICOS"),
    TRES("FDD CIRCUITOS FINANZAS POO VECTORIAL ESTRUCTURAS"),
    CUATRO("DSD WEB ADOO ANALOGICA AVANZADAS TEORIA"),
    CINCO("SEÑALES METODOS ALGORITMOS REDES SISTEMAS PROBABILIDAD"),
    SEIS("SOFTWARE PROYECTOS INSTRUMENTACION OPTATIVA"),
    SIETE("ARQUITECTURA COMPILADORES REDES2 OPTATIVA"),
    OCHO("MICROCONTROLADORES OPTATIVA OPTATIVA PROTOCOLO"),
    NUEVE("REDES3 SERVICIOS LIDERAZGO GESTION EMPRESARIAL TT1"),
    DIEZ("TT2");

    private String materias;
    private Equipo (String materias){
		this.materias = materias;
	}
    public String getMaterias() {
		return materias;
    }
}


